AllCops:
  DisplayCopNames: true
  NewCops: enable

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/BeforeAfterAll:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 150
