require: rubocop-performance

inherit_from: .oct_rubocop.yml

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/simply/web/test/**/*'
    - 'spec/spec_helper.rb'

Metrics/LineLength:
  Exclude:
    - 'Rakefile'
  IgnoredPatterns: ['description *= .*']

Metrics/MethodLength:
  Exclude:
    - 'spec/simply/web/helper/setup.rb'
    - 'Rakefile'

Style/FrozenStringLiteralComment:
  Enabled: false
