source 'https://www.rubygems.org'

gem 'capybara'
gem 'colorize'
gem 'dotenv'
gem 'faker'
gem 'faraday'
gem 'oct_gaia'
gem 'parallel_split_test'
gem 'parallel_tests'
gem 'pry-byebug'
gem 'rubocop-performance'
gem 'rubocop-rspec'
gem 'simple-secrets'
